#ifndef PLAY_CACHE_H
#define PLAY_CACHE_H

/* Auto-generated by cbindgen — do not edit.
 * Regenerate with: cargo build (build.rs runs cbindgen).
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Default cap: 500 MB in bytes.  Override with `PLAY_CACHE_MAX_BYTES`.
 */
#define DEFAULT_MAX_BYTES ((500 * 1024) * 1024)

/**
 * Opaque cache state.  The pointer is allocated via `Box::into_raw` and must
 * be freed with `cache_close`.  cbindgen emits a forward declaration so Go
 * can hold a `*CacheHandle` without knowing its layout.
 */
typedef struct CacheHandle CacheHandle;

/**
 * Open the cache from `$HOME/.play/cache.json`.
 *
 * Scans the audio directory once to initialise the `total_bytes` counter.
 * Returns an opaque handle on success, or NULL if the file cannot be loaded.
 * Must be paired with `cache_close`.
 */
struct CacheHandle *cache_open(void);

/**
 * Look up entries whose id, title, artist, query, or source contains `query`
 * (case-insensitive substring).  An empty `query` returns all entries.
 *
 * **Access promotion**: every matched entry has its `timestamp` updated to
 * `now` so that recently-read entries are not evicted first.  The updated
 * timestamps are persisted to disk so promotion survives across sessions.
 *
 * Returns a JSON array string that **must** be freed with `cache_free_string`.
 * Returns NULL on invalid arguments or internal error.
 *
 * # Safety
 * `handle` must be a valid pointer obtained from `cache_open`.
 * `query`  must be a valid null-terminated UTF-8 string.
 */
char *cache_get(struct CacheHandle *handle, const char *query);

/**
 * Add or update an entry.  `entry_json` must be a JSON object whose fields
 * match `model::CacheEntry` (id, title, source, timestamp, hit_count,
 * artist, query).  Also accepts Go's alternate key names (video_id,
 * source_type, last_used).
 *
 * Enforces the 500 MB size cap immediately after inserting via LRU eviction.
 * `total_bytes` is updated incrementally — no directory re-scan.
 *
 * Persists the updated list to disk.
 *
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `handle`     must be a valid pointer obtained from `cache_open`.
 * `entry_json` must be a valid null-terminated UTF-8 JSON string.
 */
int32_t cache_put(struct CacheHandle *handle, const char *entry_json);

/**
 * Free a string returned by `cache_get`.
 *
 * # Safety
 * `s` must have been returned by `cache_get` and not yet freed.
 * Passing NULL is safe (no-op).
 */
void cache_free_string(char *s);

/**
 * Close the handle and release all memory.
 *
 * # Safety
 * `handle` must have been returned by `cache_open` and not yet closed.
 * Passing NULL is safe (no-op).
 */
void cache_close(struct CacheHandle *handle);

#endif  /* PLAY_CACHE_H */
